config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h3>Following errors caused articles to not get saved:</h3>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %>
    <br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back to all articles list", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit article no. <%=@article.id%></h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>
<p>
  <%= link_to "Create new article", new_article_path %>
</p>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  <% @articles.each do |i| %>
    <tr>
      <td><%= i.title %></td>
      <td><%= i.description %></td>
      <td><%= link_to "Edit", edit_article_path(i) %></td>
      <td><%= link_to "Show", article_path(i) %></td>
      <td><%= link_to "Delete", article_path(i), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h2>Create new Article</h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing article no. <%=@article.id%></h1>

<h5>
  Title
</h5>
<%= @article.title %>
<h5>
  Description
</h5>
<%= @article.description %>
<p>
  <%= link_to "Edit this article", edit_article_path(@article) %>
</p>
<p>
  <%= link_to "Back to all articles list", articles_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VkyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg|%>
      <ul>
        <li><%msg%></li>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<html>

  <head>
    <title>Vky's Blog</title>
  </head>

  <body>

    <h1>Know more about Vky</h1>
    <p>You are watching it because you are alive!</p>

    <h2>Important Dates</h2>
    <p><i>November 14, 2019</i> - Vky's 28th Birthday and ... ehmmm ;-)</p>

    <h2>Links</h2>
    <p>Here is a link to
      <%= link_to 'Home', root_path %>
    </p>

  </body>

</html>

app/views/pages/home.html.erb
<html>

<head>
  <title>Vky's Blog</title>
</head>

<body>
  <h1>Welcome to Wish Raza a happy birthday</h1>
  <hr/>
  <p><% current_time = Time.now %></p>
  <p><% birthday_time = Time.new(2019, 04, 20) %></p>
  <% if (current_time > birthday_time)%>
    <h3>Happy Birthday Razuuu</h3>
  <% else %>
    <h3>
      <%= (birthday_time.to_i - current_time.to_i) / (60 * 60)%> hr |
      <%= (birthday_time.to_i - current_time.to_i) / (60)%> min |
      <%= ((birthday_time).to_i - (current_time).to_i)%> sec left for <i>Raza's birthday</i> to start
    </h3>
  <% end %>
  
  <p>
    <img src="https://scontent.flhe7-1.fna.fbcdn.net/v/t1.0-9/30708207_1717581061637893_1777589051444953088_o.jpg?_nc_cat=104&_nc_eui2=AeF3q3T80RydXQcGrbuADha9yb-cYMVcLbCXtTLE69ALhEJ5HfvOLX5JziBKFIr0BNNh0xJLa3T9ijkc15T56lkkJEieUtua2O-7r15p_1HxXA&_nc_ht=scontent.flhe7-1.fna&oh=38ad5bbcf45b2ebeea49757f3bdcda28&oe=5D2B15E7" alt="Sumail">
  </p>
  <p>
    Go to
    <%= link_to 'My blog', articles_path%> |OR|
    Know more about
    <%= link_to 'About', about_path %>
    me
  </p>
</body>

</html>